import sys, pandas as pd

# First get the drawing of the current state of the crates
input = open(sys.path[0] + '/input')
crates = []
moves = []
move_check = False

for line in input:
    if move_check == False and line == '\n':
        move_check = True
        continue
        #break
    elif move_check == False and line[0] == '[': 
        line = line.replace('\n', '').replace('    ', ' [-]').replace('[', '').replace(']', '')       
        crates.append(line.split(' '))
        # print(line)
    elif move_check == False:
        line = line.replace('\n', '').strip()
        header = line.split(' ')
        header = [item for item in header if item] # remove blanks which were generated by having consecutive delimiters
        #print(header)
    else:
        line = line.replace('\n', '')
        moves.append(line.split(' '))

# save crates as a dataframe and invert the rows
crates = pd.DataFrame(crates, columns = header)
crates = crates.iloc[::-1]
crates = crates.reset_index(drop=True)

# save moves as dataframe
moves = pd.DataFrame(moves, columns = ['', 'crate_count', '', 'from_col', '', 'to_col'])
moves = moves[['crate_count', 'from_col', 'to_col']]

# for range(crate_count): remove last crate from "from" and append to "to"
for index, row in moves.iterrows():
    crate_count = int(row['crate_count'])
    from_col = row['from_col']
    to_col = row['to_col']

    for i in range(crate_count):
        # find last-occupied row, change that cell's value to -, append that value to the destination column
        #crate = pd.DataFrame([crates[from_col].iloc[len(crates[crates[from_col] != '-']) - 1]], columns = [to_col])
        crate = crates[from_col].iloc[len(crates[crates[from_col] != '-']) - 1]
        crates[from_col].iloc[len(crates[crates[from_col] != '-']) - 1] = '-'  
        if len(crates[crates[to_col] == '-']) == 0:
            crates = pd.concat([crates, pd.DataFrame([crate], columns = [to_col])], ignore_index=True)
            crates = crates.fillna('-')
        else:
            crates[to_col].iloc[len(crates[crates[to_col] != '-'])] = crate
#print(crates)

#grab last crate in each column
msg = ''
for column in crates:
    msg = msg + crates[column].iloc[len(crates[crates[column] != '-']) - 1]

print(msg)
